version: '3'

# run tests:  cd ci/unit; docker-compose up --build --force-recreate
# manual:  cd ci/unit; docker-compose run logstash bash
services:

  logstash:
    build:
      context: ../
      dockerfile: .ci/Dockerfile
      args:
        - ELASTIC_STACK_VERSION=$ELASTIC_STACK_VERSION
        - DISTRIBUTION=${DISTRIBUTION:-default}
    command: .ci/run.sh
    env_file: docker.env
    environment:
      - SPEC_OPTS
      - LOG_LEVEL # devutils (>= 2.0.4) reads the ENV and sets LS logging
      - CI # CI=true in Travis-CI
      - TRAVIS # TRAVIS=true in Travis-CI
    tty: true
